services:
  - type: web
    name: hostel-portal-backend
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    rootDir: backend
    envVars:
      - key: MONGODB_URI
        value: mongodb+srv://shreyas777999_db_user:KQqJ9hZOXn4YXVqR@hostelp.gmlzm5p.mongodb.net/hostel_portal?appName=HostelP
      - key: DB_NAME
        value: hostel_portal
      - key: FRONTEND_URL
        value: https://transcend-360.vercel.app
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        value: a8f3b2c9d4e5f106789a012345bcde67f890123456789abcdef0123456789abc
      - key: JWT_EXPIRES_IN
        value: 30d
